# RENAME FILE TO 'config.yml'
bot:
  token: MTI2MTU3NzY4ODIwMDc3MzY4Mg.G0UkHy.yW-dMCur7xMj8FkT8uat1wCWQNcssx-SxCx2i0
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
