# RENAME FILE TO 'config.yml'
bot:
  token: 
    - MTI2Nzg2OTMyOTA2ODY1ODc4MA.GVLaSc.vyzKeqSSb_QULg5-ZGqmLrpVvqImtmhfrWEz5I
    - de990bce-09d3-443d-91db-857db322336e
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
